parameters:
#    spx_main.example.class: Spx\MainBundle\Example

services:
#    spx_main.example:
#        class: %spx_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
